sample:
  train: 300
  eval: 30
stopper:
  cost: 1000000
  duration: 5h
train:
  batch_size: 8192
  lr: 0.002
mdp:
  create:
    - lamarckian.mdp.nsh.MDP
  nsh:
    time_per_frame: 100
    gc: 1m
    task: task
    role:
      - 神像
      - 神像
    # idle relative cartesian fight
    skill:
      - Idle
      - move/Relative
      - Fight
    fight:
      - Enable
    state:
      - Cartesian
      - enemy/Cartesian
      - HP
      - enemy/HP
      - fight/Legal
      - fight/Step
      - StatusGroup
      - enemy/StatusGroup
    status_group:
      me:
        deactivate:
          - Bind
          - Frozen
          - Floating
          - Dizzy
      enemy:
        deactivate:
          - Bind
          - Frozen
          - Floating
          - Dizzy
    status:
      me:
        - Decelerate
        - Frozen
        - Floating
        - Pulled
        - HitBackward
        - ForbidFly
      enemy:
        - Decelerate
        - Frozen
        - Floating
        - Pulled
        - HitBackward
        - ForbidFly
    position:
      name: Center
      circle:
        radius: ${28 * 64}
        radius0: ${1.5 * 64}
      center:
        radius: ${0 * 64}
        delta: 1
    keyboard: ${os.path.splitext(PATH)[0]}/config/relative.tsv
    jump:
      enable: 0
      type: Space
      perfect: 3
    yhf:
      enable: 0
    engage:
      - 1
      - 0
    recover: 1
    # 0：屏蔽回血
    # 1：自然回血
    # >1：额外回血
    potion: 1
    power: 0.4
    grade: 69
    nisha: 0.4
    fake: 1
    lua: luajit
    cmd: ./GasRunner -p 1234 -n gas
    sleep: 5
    port: 23191
    debug: 1
    launch: 6
    length: 600
    log: 1
    scene:
      # 16000021（武学试炼）
      # 16000102（流派竞武）
      # 21332100001
      # 28065000001（舞阳城）
      id: 16000021
      16000021:
        center:
          - 32220
          - 31550
          - -541
        radius: ${28.1 * 64}
      16000102:
        center:
          - 36220
          - 32546
          - 1851
        radius: ${45 * 64}
    sx:
      # 寒冰护体=640442
      # 广陵散=640434
      buff:
        - 640442
        - 640434
      prop:
        - QinYi
        - ToneFire
        - ToneIce
        - ToneWind
        - NiSha
      fight:
        enable:
          - 阳关三叠
          - 高山流水
          - 关山月
          - 急曲
          - 平沙落雁
    evaluating:
      flowchart_same_skill: 1
    player_id: 21332100001
    full_power: 1
    say: 1
    flowchart:
      # Pursue KeepDist Escape Patrol Random
      # AI.AI_WXW.WXSL.WXSLFakePlayer
      # AI.FakePlayer.FakePlayerMove
      # AI.AI_WZJ2.FakePlayerTest.FakePlayerMain
      name: Pursue
      # 2 = 50, 4 = 60, 6 = 69
      level: 6
      potion: 0
      run: 1
      fight: 1
    # full_hp: 0.5
    print_datetime: 0
    profile: 0
    # 24
    scope:
      - ${15 * 64}
      - ${23 * 64}
    dashboard:
      interval: 0.5
      buffer: 100
    # IPC_SYSV IPC_POSIX ZMQ ZMQ_IPC Redis RabbitMQ
    msg: ZMQ_IPC
    zmq: 5557
    cartesian:
      move:
        - →
        - ←
        - ↑
        - ↓
        - ↙
        - ↖
        - ↘
        - ↗
      yhf:
        - ↑
        - ↓
        - ←
        - →
    speed: 39
    client: lamarckian.mdp.nsh.client.SSH
test:
  mdp:
    nsh:
      position:
        center:
          radius: -1
